

# Site settings
baseurl = ""
title = "Things that Suck"
theme = "story"
languageCode = "en-us"
paginate = 5
buildFuture = true

[[menu.social]]
  name = ""
  title = ""
  url = ""

[[menu.main]]
  name = ""
  title = ""
  url = "//"

[[menu.main]]
  name = ""
  title = ""
  url = ""

[params]
  author = "Baron Schwartz"
  twitter = "xaprb"
  classes = []

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
