

# Site settings
baseurl = "https://master.d2q2qk5zzqfwxh.amplifyapp.com"
title = "Things that Suck"
theme = "story"
languageCode = "en-us"
paginate = 5

[[menu.social]]
  name = ""
  title = ""
  url = ""

[[menu.main]]
  name = ""
  title = ""
  url = "//"

[[menu.main]]
  name = ""
  title = ""
  url = ""

[params]
  author = "Baron Schwartz"
  twitter = "xaprb"
  classes = []

